### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by hrg1000** [paesanilab/mbpol_openmm_plugin#121] opened 2018-05-03 11:44 UTC
Dear All,
I installed mbpol using the instructions in INSTALL.md file. Now I am trying to run the example. I tried 2 ways:
1) Using the mbpol builder. The mbpol_builder mbpol_config.ini generated_script_filename.py stage worked fine. When I ran the generated .py file I got a segmentation fault,
2) I used the water14_cluster.pdb file and the water14.py script, again I got a segmentation fault. I discovered that the segmentation fault is occurring at the step
simulation = app.Simulation(pdb.topology, system, integrator, platform)

I would be grateful for any advice on how to correct this fault,
Thank you
Dr. Helen Eisenberg

**Comment by zonca** [comment] 2018-05-03 12:11
have you installed with `conda`?

**Comment by hrg1000** [comment] 2018-05-06 10:16
I installed with conda and the version of openmm is openmm-7.2.1

**Comment by zonca** [comment] 2018-05-06 10:52
Which version of Python? I will try to reproduce the issue

**Comment by hrg1000** [comment] 2018-05-06 11:07
When I am in the environment I created and I link at the beginning by typing "source activate openmm_env" then it is Python 3.6.5 :: Anaconda, Inc. . I think that when I installed mbpol by typing "conda install mbpol" this version of python was installed. When I am not in this python environment then it is Python 2.7.6.

**Comment by hrg1000** [comment] 2018-05-06 11:08
Note I installed openmm before I tried to install mbpol

**Comment by hrg1000** [comment] 2018-05-08 10:17
Please note when I tried to install mbpol on another of our computers, without installing openmm first, using "conda install mbpol", I get this error message when trying to run "python water14.py":
   from simtk.openmm import app
ModuleNotFoundError: No module named 'simtk'
I see some openmm files have been installed in the directory /opt/conda/miniconda2/envs/openmm_env/include/openmm
Could it be because I am using miniconda and not the full anaconda?

**Comment by zonca** [comment] 2018-05-09 13:45
no, `miniconda` is fine, in the second case you also need to install openmm, it doesn't matter if you install OpenMM before or after mbpol.

I reproduced the segfault on my machine.
I haven't yet identified the cause yet, I'll report back once it is fixed, this sort of debugging is tricky so it will take some time.

The other option is to build from source:
https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/INSTALL.md#how-to-install-from-source

**Comment by zonca** [comment] 2018-05-09 20:57
@hrg1000 actually I think I fixed this, I just uploaded another conda package for `mbpol`, version 1.1.2, currently only for Python 3.6,
can you please try running `conda update mbpol` and check if the segfault is gone?

**Comment by hrg1000** [comment] 2018-05-13 10:01
It worked!!! Thank you so much for your help,
Helen

**Comment by zonca** [comment] 2018-05-13 11:36
Thanks for reporting, I'll build all the other versions and then close the issue

**Comment by zonca** [comment] 2018-05-13 15:44
ok, I built also Python 3.5 and 2.7, OpenMM 7.2.1 dropped 3.4 support in conda packages, so we'll do the same

**Closed by zonca** 2018-05-13 15:44 UTC
